nelmio_api_doc:
    documentation:
        info:
            title: BileMo API Documentation
            description: This is the documentation of the BileMo API.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!(_(profiler|wdt|error)|css|images|js|doc)) # Accepts routes under /api except /api/doc

